mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://dns.adguard.com/dns-query
  - https://cloudflare-dns.com/dns-query
  - https://dns.google/dns-query
  - https://doh.sb/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.localdomain'
  - '*.example'
  - '*.invalid'
  - '*.localhost'
  - '*.test'
  - '*.local'
  - '*.home.arpa'
  - router.asus.com
  - localhost.sec.qq.com
  - localhost.ptlogin2.qq.com
  - +.msftconnecttest.com
proxies:
- name: '@v2ray_market11'
  type: vmess
  server: 103.180.236.96
  port: 4050
  uuid: c0722d32-162b-46fc-961c-8c90b661e0d7
  alterId: 0
  cipher: auto
  tls: false
  network: tcp
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_1'
  type: vmess
  server: 104.19.45.203
  port: 2095
  uuid: 7a737f41-b792-4260-94ff-3d864da67b80
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@Asliveepn_1'
  type: vmess
  server: us-21.hihu.net
  port: 80
  uuid: 6385d460-609f-11ef-b936-205c6d5f5d78
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@Asliveepn_2'
  type: vmess
  server: 104.21.28.62
  port: 443
  uuid: 1052f24e-7b09-45eb-b0c5-d858eb124192
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_2'
  type: vmess
  server: hms24.ivideos.sbs
  port: 443
  uuid: 441da342-ce90-441e-bff9-d2ceb55e68ca
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_3'
  type: vmess
  server: 172.67.196.112
  port: 443
  uuid: edbb1059-1633-4271-b66e-ed4fba47a1bf
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_4'
  type: vmess
  server: 172.67.219.194
  port: 443
  uuid: b321fd5d-e6ec-4293-a644-164e3885f52e
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_5'
  type: vmess
  server: 104.21.54.209
  port: 2053
  uuid: a04001f3-2dba-40ed-8c2e-d0c765d9afaa
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@asliveepn_6'
  type: vmess
  server: 104.21.83.108
  port: 443
  uuid: 6c168fcc-2231-4f3b-8c1e-f6391692df4a
  alterId: 0
  cipher: auto
  tls: true
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
- name: '@Asliveepn_3'
  type: vmess
  server: slime-rhinestone-spy.glitch.me
  port: 80
  uuid: 83a5c82d-a047-418e-9ad9-6ce8c5aaba59
  alterId: 0
  cipher: auto
  tls: false
  network: ws
  ws-opts:
    headers: {}
    path: ''
  alpn: null
proxy-groups:
- name: 🚀 节点选择
  type: select
  proxies:
  - '@v2ray_market11'
  - '@asliveepn_1'
  - '@Asliveepn_1'
  - '@Asliveepn_2'
  - '@asliveepn_2'
  - '@asliveepn_3'
  - '@asliveepn_4'
  - '@asliveepn_5'
  - '@asliveepn_6'
  - '@Asliveepn_3'
- name: ♻️ 自动选择
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - '@v2ray_market11'
  - '@asliveepn_1'
  - '@Asliveepn_1'
  - '@Asliveepn_2'
  - '@asliveepn_2'
  - '@asliveepn_3'
  - '@asliveepn_4'
  - '@asliveepn_5'
  - '@asliveepn_6'
  - '@Asliveepn_3'
rules:
- GEOIP,CN,DIRECT
- MATCH,🐟 漏网之鱼
